function [U, info] = tucker_gmres_left_preconditioned_fixed( ...
    A, P, F0, U0, ...
    maxit, tol, eta, ...
    true_residual, precond_residual, ...
    verbose, max_basis_entries, ...
    max_rank, check_it)
%TUCKER_GMRES_LEFT_PRECONDITIONED_FIXED Fixed-tolerance control method.

if nargin < 10
    verbose = false;
end

if nargin < 11
    max_basis_entries = Inf;
end

if nargin < 12
    max_rank = [];
end
if nargin < 13
    check_it = [];
end

[U, info] = run_left_preconditioned_tucker_gmres_cycle( ...
    A, P, F0, U0, ...
    maxit, tol, eta, "fixed", ...
    true_residual, precond_residual, ...
    verbose, max_basis_entries, ...
    max_rank, tol, 1 - eps, ...
    check_it);

end
