function [U, info] = tucker_gmres_left_preconditioned_relaxed( ...
    A, P, F0, U0, ...
    maxit, tol, ...
    true_residual, precond_residual, ...
    verbose, max_basis_entries, ...
    max_rank)
%TUCKER_GMRES_LEFT_PRECONDITIONED_RELAXED Apply the Section 5.5 rule.

if nargin < 9
    verbose = false;
end

if nargin < 10
    max_basis_entries = Inf;
end

if nargin < 11
    max_rank = [];
end

[U, info] = run_left_preconditioned_tucker_gmres_cycle( ...
    A, P, F0, U0, ...
    maxit, tol, tol, "relaxed", ...
    true_residual, precond_residual, ...
    verbose, max_basis_entries, ...
    max_rank);

end
