function test_poisson_preconditioned_tucker_gmres
%TEST_POISSON_PRECONDITIONED_TUCKER_GMRES Validate Algorithms 5.7--5.8.
%
% These small tests check four claims used by the numerical experiment:
%
%   1. STHOSVD meets its tolerance when the rank cap is inactive and
%      reports when a hard rank cap overrides that tolerance.
%   2. The Tucker exponential-sum preconditioner agrees with a directly
%      assembled dense reference on a tiny three-dimensional grid.
%   3. The spectral diagnostic agrees with the explicit eigenvalues of
%      the tiny preconditioned matrix.
%   4. The fixed and relaxed left-preconditioned solvers use one
%      Gram--Schmidt pass, report the original true residual, and implement
%      the stated residual-based tolerance schedule.
%
% These are correctness tests, not performance experiments.


%% 0. Prepare MATLAB and Tensor Toolbox

add_toolboxes();
rng(7, 'twister');

fprintf('\nStarting preconditioned Tucker-GMRES tests.\n\n');


%% Test 1. STHOSVD tolerance and hard rank cap

fprintf('Test 1: STHOSVD tolerance and hard rank cap...\n');

Xfull = tensor(randn(4, 4, 4));
X = hosvd(Xfull, 1e-13, 'verbosity', 0);

[Xinexact, inactiveInfo] = tucker_round(X, 1e-6, [4, 4, 4]);
inactiveError = norm(Xfull - full(Xinexact)) / norm(Xfull);

assert(~inactiveInfo.rank_cap_active, ...
    'The full mode-size cap should be inactive.');
assert(inactiveError <= 1.01e-6, ...
    'STHOSVD did not meet its requested relative tolerance.');

[Xcapped, activeInfo] = tucker_round(X, 1e-12, [2, 2, 2]);
activeRanks = size(Xcapped.core);

assert(activeInfo.rank_cap_active, ...
    'The rank-two cap should be reported as active.');
assert(all(activeRanks <= [2, 2, 2]), ...
    'The recompressed tensor exceeded the hard rank cap.');

fprintf('  Inactive-cap relative error: %.3e\n', inactiveError);
fprintf('  Active-cap retained ranks: [%s]\n', ...
    strjoin(string(activeRanks), ', '));
fprintf('  Test 1 passed.\n\n');


%% Test 2. Exponential-sum preconditioner versus a dense reference

fprintf('Test 2: Tucker preconditioner versus dense reference...\n');

N = 4;
numberOfModes = 3;
h = 1 / (N + 1);
onesVector = ones(N, 1);

A1 = spdiags( ...
    [-onesVector, 2 * onesVector, -onesVector], ...
    -1:1, N, N) / h^2;

q = 6;
preconditioner = build_poisson_exponential_sum_preconditioner( ...
    A1, numberOfModes, q);

Yfull = tensor(randn(N, N, N));
Y = hosvd(Yfull, 1e-13, 'verbosity', 0);

[Z, preconditionerInfo] = ...
    apply_poisson_exponential_sum_preconditioner( ...
        Y, preconditioner, 1e-12, [N, N, N]);

densePreconditioner = zeros(N^numberOfModes);

for termIndex = 1:preconditioner.number_of_terms

    tau = preconditioner.tau(termIndex);
    omega = preconditioner.omega(termIndex);

    oneDimensionalExponential = ...
        expm(-tau * full(A1));

    densePreconditioner = densePreconditioner + omega * ...
        kron(oneDimensionalExponential, ...
             kron(oneDimensionalExponential, ...
                  oneDimensionalExponential));

end

Yvalues = double(Yfull);
Zvalues = double(full(Z));
denseReference = densePreconditioner * Yvalues(:);

preconditionerActionError = ...
    norm(Zvalues(:) - denseReference) / norm(denseReference);

assert(preconditionerActionError < 1e-10, ...
    'The Tucker preconditioner does not match the dense reference.');
assert(~preconditionerInfo.rank_cap_active, ...
    'The full mode-size rank cap should remain inactive.');

fprintf('  Relative action error: %.3e\n', ...
    preconditionerActionError);
fprintf('  Test 2 passed.\n\n');


%% Test 3. Spectral diagnostic versus the explicit matrix

fprintf('Test 3: preconditioned spectrum diagnostic...\n');

identityMatrix = speye(N);
densePoisson = ...
    kron(identityMatrix, kron(identityMatrix, A1)) + ...
    kron(identityMatrix, kron(A1, identityMatrix)) + ...
    kron(A1, kron(identityMatrix, identityMatrix));

explicitPreconditionedEigenvalues = eig( ...
    densePreconditioner * full(densePoisson));
explicitPreconditionedEigenvalues = ...
    real(explicitPreconditionedEigenvalues);

diagnostic = diagnose_poisson_exponential_sum_preconditioner( ...
    preconditioner, true, 5001);

explicitMinimum = min(explicitPreconditionedEigenvalues);
explicitMaximum = max(explicitPreconditionedEigenvalues);
explicitDelta = max(abs(1 - explicitPreconditionedEigenvalues));

assert(abs(diagnostic.exact_minimum_preconditioned_eigenvalue - ...
    explicitMinimum) < 1e-10, ...
    'The diagnostic minimum eigenvalue is inconsistent.');
assert(abs(diagnostic.exact_maximum_preconditioned_eigenvalue - ...
    explicitMaximum) < 1e-10, ...
    'The diagnostic maximum eigenvalue is inconsistent.');
assert(abs(diagnostic.exact_delta - explicitDelta) < 1e-10, ...
    'The diagnostic spectral error is inconsistent.');

fprintf('  Exact condition number: %.6f\n', ...
    diagnostic.exact_condition_number);
fprintf('  Maximum |1-lambda*mu_q(lambda)|: %.3e\n', ...
    diagnostic.exact_delta);
fprintf('  Test 3 passed.\n\n');


%% Test 4. Fixed and relaxed left-preconditioned solvers

fprintf('Test 4: fixed and relaxed left-preconditioned solvers...\n');

exactSolutionFull = tensor(randn(N, N, N));
exactSolution = hosvd(exactSolutionFull, 1e-13, 'verbosity', 0);

[F, poissonInfo] = poisson_action_tucker( ...
    exactSolution, A1, 1e-13, [N, N, N]);
U0 = 0 * F;

assert(isfield(poissonInfo, 'kernel_timing') && ...
       poissonInfo.kernel_timing.poisson_mode_product_time_sec >= 0 && ...
       poissonInfo.kernel_timing.sthosvd_svd_time_sec >= 0, ...
    'The Poisson action did not return valid kernel timings.');

operatorFunction = @(U, tolerance, maximumRanks) ...
    poisson_action_tucker(U, A1, tolerance, maximumRanks);

preconditionerFunction = @(Yinput, tolerance, maximumRanks) ...
    apply_poisson_exponential_sum_preconditioner( ...
        Yinput, preconditioner, tolerance, maximumRanks);

originalTrueResidualFunction = @(U) ...
    true_residual_tucker_poisson(U, F, A1);

diagnosticTolerance = 1e-12;
preconditionedResidualNormFunction = @(U) ...
    preconditioned_residual_norm_tucker_poisson( ...
        U, F, A1, preconditioner, diagnosticTolerance);

targetTolerance = 1e-7;
fixedCompressionTolerance = 1e-10;
maximumIteration = 8;
maximumRanks = [N, N, N];

[Ufixed, fixedInfo] = tucker_gmres_left_preconditioned_fixed( ...
    operatorFunction, preconditionerFunction, F, U0, ...
    maximumIteration, targetTolerance, fixedCompressionTolerance, ...
    originalTrueResidualFunction, preconditionedResidualNormFunction, ...
    false, Inf, maximumRanks, 1);

[Urelaxed, relaxedInfo] = ...
    tucker_gmres_left_preconditioned_relaxed( ...
        operatorFunction, preconditionerFunction, F, U0, ...
        maximumIteration, targetTolerance, ...
        originalTrueResidualFunction, ...
        preconditionedResidualNormFunction, ...
        false, Inf, maximumRanks);

fixedResidual = originalTrueResidualFunction(Ufixed);
relaxedResidual = originalTrueResidualFunction(Urelaxed);

assert(fixedInfo.orthogonalisation_passes == 1, ...
    'The fixed solver must use one Gram--Schmidt pass.');
assert(relaxedInfo.orthogonalisation_passes == 1, ...
    'The relaxed solver must use one Gram--Schmidt pass.');
assert(abs(fixedInfo.true_relative_residual(end) - fixedResidual) < ...
    1e-12, ...
    'The fixed solver did not report the original true residual.');
assert(abs(relaxedInfo.true_relative_residual(end) - relaxedResidual) < ...
    1e-12, ...
    'The relaxed solver did not report the original true residual.');
assert(fixedInfo.solution_assembly_count == 1 && ...
        relaxedInfo.solution_assembly_count == 1, ...
    'Each unrestarted preconditioned solver should assemble once.');
assert(size(fixedInfo.solution_ranks, 1) == 1 && ...
        size(relaxedInfo.solution_ranks, 1) == 1, ...
    'Solution ranks should be recorded only at delayed assembly.');
assert(isequal(fixedInfo.true_residual_iteration(1:2), [0; 1]) && ...
       fixedInfo.true_residual_iteration(end) == fixedInfo.iterations, ...
    'The fixed solver did not record its requested checkpoint.');
assert(isequal(relaxedInfo.true_residual_iteration, ...
        [0; relaxedInfo.iterations]), ...
    'The relaxed solver should evaluate true residuals at cycle endpoints.');
assert(numel(fixedInfo.computed_preconditioned_relative_residual) == ...
        fixedInfo.iterations && ...
       numel(relaxedInfo.computed_preconditioned_relative_residual) == ...
        relaxedInfo.iterations, ...
    'Computed residuals should still be recorded at every Arnoldi step.');
assert(~fixedInfo.rank_cap_active && ~relaxedInfo.rank_cap_active, ...
    'The full mode-size rank cap should remain inactive.');

assert_cycle_timing_profile(fixedInfo);
assert_cycle_timing_profile(relaxedInfo);

assert(abs(relaxedInfo.eta(1) - targetTolerance) < ...
    10 * eps(targetTolerance), ...
    'The first relaxed tolerance must equal the target tolerance.');

for iteration = 2:relaxedInfo.iterations

    expectedEta = targetTolerance / ...
        relaxedInfo.computed_preconditioned_relative_residual( ...
            iteration - 1);
    expectedEta = min(expectedEta, 1 - eps);

    assert(abs(relaxedInfo.eta(iteration) - expectedEta) <= ...
        100 * eps(max(1, expectedEta)), ...
        'The relaxed tolerance does not follow the residual rule.');

end

assert(fixedResidual < 1e-5, ...
    'The fixed left-preconditioned solve did not reduce the residual.');
assert(relaxedResidual < 1e-5, ...
    'The relaxed left-preconditioned solve did not reduce the residual.');

fprintf('  Fixed final true residual: %.3e\n', fixedResidual);
fprintf('  Relaxed final true residual: %.3e\n', relaxedResidual);


%% Test 5. Capped relaxed schedule with separate thresholds

fprintf('Test 5: capped relaxed schedule...\n');

internalStoppingTolerance = 1e-12;
relaxationErrorBudget = 1e-8;
maximumRelaxedTolerance = 1e-7;

[Ucapped, cappedInfo] = ...
    tucker_gmres_left_preconditioned_capped_relaxed( ...
        operatorFunction, preconditionerFunction, F, U0, ...
        maximumIteration, internalStoppingTolerance, ...
        relaxationErrorBudget, maximumRelaxedTolerance, ...
        originalTrueResidualFunction, ...
        preconditionedResidualNormFunction, ...
        false, Inf, maximumRanks);

cappedResidual = originalTrueResidualFunction(Ucapped);

assert(abs(cappedInfo.target_tolerance - ...
    internalStoppingTolerance) < eps, ...
    'The capped solver did not preserve its internal stopping threshold.');
assert(abs(cappedInfo.relaxation_error_budget - ...
    relaxationErrorBudget) < eps, ...
    'The capped solver did not preserve its relaxation error budget.');
assert(abs(cappedInfo.maximum_relaxed_tolerance - ...
    maximumRelaxedTolerance) < eps, ...
    'The capped solver did not preserve its tolerance cap.');

expectedCappedEta = zeros(cappedInfo.iterations, 1);
previousComputedRelativeResidual = 1;

for iteration = 1:cappedInfo.iterations

    expectedCappedEta(iteration) = min( ...
        maximumRelaxedTolerance, ...
        relaxationErrorBudget / previousComputedRelativeResidual);

    previousComputedRelativeResidual = ...
        cappedInfo.computed_preconditioned_relative_residual(iteration);

end

assert(max(abs(cappedInfo.eta - expectedCappedEta)) <= ...
    100 * eps(max(1, max(expectedCappedEta))), ...
    'The capped solver does not follow its declared schedule.');
assert(all(cappedInfo.eta <= maximumRelaxedTolerance), ...
    'The capped solver exceeded its maximum relaxed tolerance.');
assert(abs(cappedInfo.true_relative_residual(end) - ...
    cappedResidual) < 1e-12, ...
    'The capped solver did not report the original true residual.');
assert(~cappedInfo.rank_cap_active, ...
    'The full mode-size rank cap should remain inactive.');

fprintf('  Final true residual: %.3e\n', cappedResidual);
fprintf('  Maximum requested tolerance: %.3e\n', ...
    max(cappedInfo.eta));
fprintf('  Test 5 passed.\n\n');


%% Test 6. Restarted relaxed schedule

fprintf('Test 6: restarted relaxed schedule...\n');

[Urestarted, restartedInfo] = ...
    tucker_gmres_left_preconditioned_relaxed_restarted( ...
        operatorFunction, preconditionerFunction, F, U0, ...
        2, 4, targetTolerance, ...
        originalTrueResidualFunction, ...
        preconditionedResidualNormFunction, ...
        false, Inf, maximumRanks);

cycleStartLocations = find(restartedInfo.local_iteration == 1);

assert(~isempty(cycleStartLocations), ...
    'The restarted solver did not complete an Arnoldi step.');
assert(all(abs(restartedInfo.eta(cycleStartLocations) - ...
    targetTolerance) < 10 * eps(targetTolerance)), ...
    'The relaxed tolerance did not reset at a cycle start.');
assert(restartedInfo.orthogonalisation_passes == 1, ...
    'The restarted solver must use one Gram--Schmidt pass.');
assert(restartedInfo.solution_assembly_count == ...
        restartedInfo.number_of_cycles, ...
    'The restarted solver should assemble once per completed cycle.');
assert(length(restartedInfo.true_relative_residual) == ...
        restartedInfo.number_of_cycles + 1, ...
    'Original true residuals should occur only at restart boundaries.');
assert(isequal(restartedInfo.solution_rank_iteration, ...
        cumsum(restartedInfo.cycle_iterations)), ...
    'Restarted solution ranks should occur at cycle endpoints.');
assert(~restartedInfo.rank_cap_active, ...
    'The full mode-size rank cap should remain inactive.');

restartedResidual = originalTrueResidualFunction(Urestarted);

assert(abs(restartedInfo.true_relative_residual(end) - ...
    restartedResidual) < 1e-12, ...
    'The restarted solver did not report the original true residual.');
assert(restartedResidual < 1e-4, ...
    'The restarted relaxed solve did not reduce the residual enough.');

fprintf('  Completed cycles: %d\n', restartedInfo.number_of_cycles);
fprintf('  Restarted final true residual: %.3e\n', ...
    restartedResidual);
fprintf('  Test 6 passed.\n\n');

fprintf('All preconditioned Tucker-GMRES tests passed.\n');

end


function assert_cycle_timing_profile(info)
%ASSERT_CYCLE_TIMING_PROFILE Check the non-overlapping timing account.

assert(isfield(info, 'timing'), ...
    'The solver did not return its detailed timing profile.');

timing = info.timing;
requiredNonnegativeFields = { ...
    'operator_application_time_sec', ...
    'preconditioner_application_time_sec', ...
    'outer_round_time_sec', ...
    'initial_residual_formation_time_sec', ...
    'orthogonalisation_inner_product_time_sec', ...
    'orthogonalisation_subtraction_round_time_sec', ...
    'small_least_squares_time_sec', ...
    'basis_normalisation_time_sec', ...
    'solution_assembly_time_sec', ...
    'original_true_residual_time_sec', ...
    'preconditioned_residual_diagnostic_time_sec'};

for fieldIndex = 1:numel(requiredNonnegativeFields)
    fieldName = requiredNonnegativeFields{fieldIndex};
    assert(isfield(timing, fieldName), ...
        'A required solver timing field is missing.');
    assert(isfinite(timing.(fieldName)) && timing.(fieldName) >= 0, ...
        'A solver timing field is negative or non-finite.');
end

assert(abs(timing.solver_time_sec - info.solver_time_sec) <= ...
    10 * eps(max(1, info.solver_time_sec)), ...
    'The detailed and legacy solver totals disagree.');
assert(abs(timing.diagnostic_time_sec - info.diagnostic_time_sec) <= ...
    10 * eps(max(1, info.diagnostic_time_sec)), ...
    'The detailed and legacy diagnostic totals disagree.');
assert(abs(timing.accounted_solver_time_sec + ...
        timing.unclassified_solver_time_sec - timing.solver_time_sec) <= ...
    100 * eps(max(1, timing.solver_time_sec)), ...
    'The solver phase timings do not close to the solver total.');
assert(abs(timing.accounted_diagnostic_time_sec + ...
        timing.unclassified_diagnostic_time_sec - ...
        timing.diagnostic_time_sec) <= ...
    100 * eps(max(1, timing.diagnostic_time_sec)), ...
    'The diagnostic phase timings do not close to the diagnostic total.');
assert(timing.unclassified_solver_time_sec >= ...
        -1e-6 * max(1, timing.solver_time_sec), ...
    'The named solver phases double-count a material amount of time.');
assert(timing.unclassified_diagnostic_time_sec >= ...
        -1e-6 * max(1, timing.diagnostic_time_sec), ...
    'The named diagnostic phases double-count a material amount of time.');

assert(numel(timing.operator_application_history_sec) == info.iterations, ...
    'The operator timing history has the wrong length.');
assert(numel(timing.orthogonalisation_subtraction_round_history_sec) == ...
        info.iterations, ...
    'The orthogonalisation timing history has the wrong length.');
assert(numel(timing.accounted_arnoldi_iteration_history_sec) == ...
        info.iterations, ...
    'The accounted iteration timing history has the wrong length.');

kernelFields = fieldnames(empty_tucker_kernel_timing());
kernelTotal = 0;

for fieldIndex = 1:numel(kernelFields)
    fieldName = kernelFields{fieldIndex};
    assert(isfinite(timing.kernel.(fieldName)) && ...
            timing.kernel.(fieldName) >= 0, ...
        'A leaf-kernel timing field is negative or non-finite.');
    kernelTotal = kernelTotal + timing.kernel.(fieldName);
end

assert(kernelTotal <= timing.solver_time_sec + ...
        1e-6 * max(1, timing.solver_time_sec), ...
    'The leaf-kernel timings double-count a material amount of solver time.');

end
