function test_tucker_roundsum_rhosvd
%TEST_TUCKER_ROUNDSUM_RHOSVD Validate RoundSum and Algorithm 5.8.

add_toolboxes();
rng(43, 'twister');

%% 1. Compare RoundSum with an exact small weighted sum

n = [5, 4, 3];
X = hosvd(tensor(randn(n)), 1e-13, 'verbosity', 0);
Y = hosvd(tensor(randn(n)), 1e-13, 'verbosity', 0);
coeff = [1.3; -0.45];
exact_sum = tucker_axpby_exact(X, coeff(1), Y, coeff(2));

[round_sum, round_info] = tucker_roundsum_rhosvd( ...
    {X; Y}, coeff, n, 1e-13, ...
    n, 701);
[same_round_sum, same_round_info] = tucker_roundsum_rhosvd( ...
    {X; Y}, coeff, n, 1e-13, ...
    n, 701);
[no_diagnostic_round_sum, no_diagnostic_info] = tucker_roundsum_rhosvd( ...
    {X; Y}, coeff, n, 1e-13, ...
    n, 701, false);

round_sum_relative_error = norm(full(round_sum) - full(exact_sum)) / ...
    norm(full(exact_sum));
reproducibility_error = norm(full(round_sum) - full(same_round_sum)) / ...
    norm(full(round_sum));
diagnostic_switch_error = norm( ...
    full(round_sum) - full(no_diagnostic_round_sum)) / norm(full(round_sum));

assert(round_sum_relative_error < 1e-11, ...
    'Full-range RoundSum does not reproduce the small exact Tucker sum.');
assert(reproducibility_error < 1e-14, ...
    'The same RoundSum seed did not reproduce the result.');
assert(diagnostic_switch_error < 1e-14, ...
    'Disabling error diagnostics changed the RoundSum output.');
assert(~no_diagnostic_info.error_diagnostics_measured && ...
    no_diagnostic_info.error_diagnostic_time_sec == 0 && ...
    isnan(no_diagnostic_info.relative_range_error) && ...
    isnan(no_diagnostic_info.relative_total_error), ...
    'The RoundSum timing switch did not suppress exact error diagnostics.');
assert(round_info.map_distribution == "standard_normal", ...
    'RoundSum did not report standard Gaussian factor matrices.');
assert(round_info.map_factor_entry_variance == 1, ...
    'RoundSum reported the wrong Gaussian variance.');
assert(round_info.maps_are_new_for_call && ...
    same_round_info.maps_are_new_for_call, ...
    'A nonzero RoundSum call must draw a new map collection.');

maps_one = create_tucker_roundsum_maps( ...
    n, n, 701);
maps_two = create_tucker_roundsum_maps( ...
    n, n, 702);
assert(~isequal(maps_one.factors{1}{2}, maps_two.factors{1}{2}), ...
    'Different RoundSum seeds produced identical factor maps.');

rank_constraint_caught = false;
try
    tucker_roundsum_rhosvd( ...
        {X; Y}, coeff, [2, 2, 2], 1e-10, [3, 2, 2], 703);
catch exception
    rank_constraint_caught = contains(exception.message, 'R_n <= k_n');
end
assert(rank_constraint_caught, ...
    'RoundSum did not enforce the condition R_n <= k_n.');

%% 2. Check the exact fixed-linear residual column in Algorithm 5.8

N = 6;
h = 1 / (N + 1);
e = ones(N, 1);
A1 = spdiags( ...
    [-e, 2 * e, -e], -1:1, N, N) / h^2;
grid_points = (1:N).' / (N + 1);
g = exp(-10 * (grid_points - 1/2).^2);
F = ttensor(tensor(1, [1, 1, 1]), ...
    {g, g, g});
U0 = 0 * F;
norm_f = norm(F);

A_terms = @(U) poisson_action_tucker_terms(U, A1);
original_residual_function = @(U) ...
    true_residual_tucker_poisson(U, F, A1);
precond_residual = @(U) ...
    norm_f * true_residual_tucker_poisson(U, F, A1);
sketch = create_tucker_row_khatri_rao_sketch( ...
    [N, N, N], 30, 811);

basis_opts.range_sketch_sizes = [N, N, N];
basis_opts.compression_tolerance = 1e-12;
basis_opts.maximum_ranks = [N, N, N];
basis_opts.random_seed = 1200;
basis_opts.algorithm_variant = "exact_sketch_before_roundsum";
basis_opts.adaptive_rank_selection = false;
solution_opts = basis_opts;
solution_opts.random_seed = 2200;

[~, solver_info] = tucker_sgmres_left_preconditioned_rhosvd( ...
    A_terms, @identity_tucker_fixed_linear_preconditioner, ...
    F, U0, 4, sketch, 1e-14, 2, ...
    basis_opts, solution_opts, original_residual_function, ...
    precond_residual, false, Inf);

V1 = (1 / norm_f) * F;
[first_operator_terms, first_operator_coefficients] = ...
    poisson_action_tucker_terms(V1, A1);
expected_first_column = apply_tucker_row_khatri_rao_sketch_sum( ...
    first_operator_terms, first_operator_coefficients, sketch);
first_column_relative_error = norm( ...
    solver_info.C(:, 1) - expected_first_column) / norm(expected_first_column);

assert(first_column_relative_error < 1e-11, ...
    'The first residual column was not sketched before RoundSum.');
assert(solver_info.exact_fixed_linear_sketch_before_roundsum, ...
    'The solver did not report the exact sketch-before-rounding contract.');
assert(~solver_info.fixed_linear_preconditioner_rounding_performed, ...
    'The solver allowed recompression inside the fixed preconditioner.');
assert(numel(unique(solver_info.basis_roundsum_seeds)) == ...
    numel(solver_info.basis_roundsum_seeds), ...
    'The solver reused a RoundSum seed inside one cycle.');
assert(all(diff(solver_info.basis_roundsum_seeds) == 1), ...
    'The basis RoundSum seed schedule is not the fresh-map rule.');
assert(isfinite(solver_info.true_relative_residual(end)), ...
    'The independently evaluated final true residual is not finite.');
assert(solver_info.true_relative_residual(end) < ...
    solver_info.true_relative_residual(1), ...
    'The RHOSVD Tucker sGMRES smoke test did not reduce the true residual.');

%% 3. Check that the omitted option defaults to paper-order Algorithm 5.8

paper_opts.compression_tolerance = 1e-12;
paper_opts.random_seed = 3100;
paper_opts.measure_error_diagnostics = true;
paper_opts.adaptive_rank_selection = true;
paper_opts.oversampling = 2;
paper_opts.maximum_rank = N;
paper_solution_settings = paper_opts;
paper_solution_settings.random_seed = 4100;

[~, paper_info] = tucker_sgmres_left_preconditioned_rhosvd( ...
    A_terms, @identity_tucker_fixed_linear_preconditioner, ...
    F, U0, 4, sketch, 1e-14, 2, paper_opts, ...
    paper_solution_settings, original_residual_function, ...
    precond_residual, false, Inf, [2; 4]);

[rounded_initial_residual, ~] = tucker_roundsum_rhosvd_adaptive( ...
    {F}, 1, paper_opts.oversampling, ...
    paper_opts.compression_tolerance, paper_opts.maximum_rank, ...
    paper_opts.random_seed, true);
paper_v1 = (1 / norm(rounded_initial_residual)) * rounded_initial_residual;
[paper_operator_terms, paper_operator_coefficients] = ...
    poisson_action_tucker_terms(paper_v1, A1);
[rounded_paper_operator, adaptive_info] = ...
    tucker_roundsum_rhosvd_adaptive( ...
    paper_operator_terms, paper_operator_coefficients, ...
    paper_opts.oversampling, paper_opts.compression_tolerance, ...
    paper_opts.maximum_rank, paper_opts.random_seed + 1, true);
expected_paper_first_column = apply_tucker_row_khatri_rao_sketch( ...
    rounded_paper_operator, sketch);
paper_first_column_relative_error = norm( ...
    paper_info.C(:, 1) - expected_paper_first_column) / ...
    norm(expected_paper_first_column);

assert(paper_first_column_relative_error < 1e-11, ...
    'The paper-order path did not sketch the rounded operator result.');
assert(~paper_info.exact_fixed_linear_sketch_before_roundsum && ...
    paper_info.rounded_operator_sketch_after_roundsum, ...
    'The paper-order sketch contract was not reported correctly.');
assert(paper_info.algorithm_variant == "paper_order", ...
    'An omitted algorithm_variant did not select paper_order.');
assert(paper_info.batch_local_projection_coefficients && ...
    ~paper_info.local_mgs_is_batch_formula_adaptation, ...
    'The paper-order path did not use batch local coeff.');
assert(adaptive_info.adaptive_rank_selection && ...
    all(adaptive_info.effective_rank_estimates >= 1), ...
    'Adaptive RoundSum did not report valid effective ranks.');
assert(paper_info.true_relative_residual(end) < ...
    paper_info.true_relative_residual(1), ...
    'The paper-order Algorithm 5.8 smoke test did not reduce the residual.');
assert(isequal(paper_info.true_residual_iteration, [0; 2; 4]), ...
    'The paper-order path did not record the requested checkpoints.');
assert(numel(paper_info.true_relative_residual) == 3 && ...
    all(isfinite(paper_info.true_relative_residual)), ...
    'The RHOSVD checkpoint true-residual history is incomplete.');

%% 4. Check safe return for an already solved initial system

identity_terms_function = @(U) one_term_identity_operator(U);
identity_true_residual = @(U) ...
    norm(tucker_axpby_exact(F, 1, U, -1)) / norm_f;
identity_residual_norm = @(U) ...
    norm(tucker_axpby_exact(F, 1, U, -1));

[zero_solution, zero_info] = ...
    tucker_sgmres_left_preconditioned_rhosvd( ...
    identity_terms_function, @identity_tucker_fixed_linear_preconditioner, ...
    F, F, 2, sketch, 1e-12, 1, basis_opts, ...
    solution_opts, identity_true_residual, identity_residual_norm, ...
    false, Inf);

assert(zero_info.iterations == 0 && ...
    zero_info.stop_reason == "zero_initial_residual", ...
    'The zero initial residual safeguard did not return before division.');
assert(norm(full(zero_solution) - full(F)) == 0, ...
    'The zero residual safeguard changed the exact initial solution.');

%% 5. Reject a preconditioner that rounds before the sketch

rounded_preconditioner_caught = false;
try
    tucker_sgmres_left_preconditioned_rhosvd( ...
        A_terms, @invalid_rounded_preconditioner, ...
        F, U0, 2, sketch, 1e-12, 1, basis_opts, ...
        solution_opts, original_residual_function, ...
        precond_residual, false, Inf);
catch exception
    rounded_preconditioner_caught = contains( ...
        exception.message, 'fixed and linear');
end
assert(rounded_preconditioner_caught, ...
    'The solver accepted recompression inside the fixed preconditioner.');

fprintf('\nRHOSVD RoundSum and Tucker sGMRES correctness test\n');
fprintf('Full-range RoundSum relative error     %.3e\n', ...
    round_sum_relative_error);
fprintf('Repeated-seed reproducibility error    %.3e\n', ...
    reproducibility_error);
fprintf('Diagnostic-switch output error         %.3e\n', ...
    diagnostic_switch_error);
fprintf('Exact first sketch-column error        %.3e\n', ...
    first_column_relative_error);
fprintf('Paper-order first-column error         %.3e\n', ...
    paper_first_column_relative_error);
fprintf('Four-step final true residual          %.3e\n', ...
    solver_info.true_relative_residual(end));
fprintf('All RHOSVD safeguards passed.\n\n');

end

function [terms, coeff, info] = one_term_identity_operator(U)
%ONE_TERM_IDENTITY_OPERATOR Exact formal representation of I(U).

terms = {U};
coeff = 1;
info.rounding_performed = false;

end

function [Z, info] = invalid_rounded_preconditioner(Y)
%INVALID_ROUNDED_PRECONDITIONER Deliberately violate the solver contract.

Z = Y;
info.rounding_performed = true;

end
