function test_tucker_gmres_algorithms
%TEST_TUCKER_GMRES_ALGORITHMS Check fixed and relaxed Tucker GMRES paths.

add_toolboxes();
rng(20260822, 'twister');

N = 4;
h = 1 / (N + 1);
onesVector = ones(N, 1);
A1 = spdiags( ...
    [-onesVector, 2 * onesVector, -onesVector], ...
    -1:1, N, N) / h^2;
maximumRanks = [N, N, N];

exactSolution = hosvd(tensor(randn(N, N, N)), ...
    1e-13, 'verbosity', 0);
[F, ~] = poisson_action_tucker( ...
    exactSolution, A1, 1e-13, maximumRanks);
U0 = 0 * F;

[preconditioner, ~] = ...
    build_poisson_fast_diagonalization_tucker_preconditioner(A1, 1);

operatorFunction = @(U, tolerance, ranks) ...
    poisson_action_tucker(U, A1, tolerance, ranks);
preconditionerFunction = @(Y, tolerance, ranks) ...
    apply_poisson_fast_diagonalization_tucker_preconditioner( ...
        Y, preconditioner, tolerance, ranks);
trueResidualFunction = @(U) true_residual_tucker_poisson(U, F, A1);
preconditionedResidualFunction = @(U) ...
    preconditioned_residual_norm_tucker_poisson_fast_diagonalization( ...
        U, F, A1, preconditioner, 1e-12);

maximumIteration = 4;
[Ufixed, fixedInfo] = tucker_gmres_left_preconditioned_fixed( ...
    operatorFunction, preconditionerFunction, F, U0, ...
    maximumIteration, 1e-14, 1e-10, ...
    trueResidualFunction, preconditionedResidualFunction, ...
    false, Inf, maximumRanks);

[Urelaxed, relaxedInfo] = tucker_gmres_left_preconditioned_relaxed( ...
    operatorFunction, preconditionerFunction, F, U0, ...
    maximumIteration, 1e-10, ...
    trueResidualFunction, preconditionedResidualFunction, ...
    false, Inf, maximumRanks);

[Ucapped, cappedInfo] = ...
    tucker_gmres_left_preconditioned_capped_relaxed( ...
        operatorFunction, preconditionerFunction, F, U0, ...
        maximumIteration, 1e-14, 1e-10, 1e-2, ...
        trueResidualFunction, preconditionedResidualFunction, ...
        false, Inf, maximumRanks);

solutions = {Ufixed, Urelaxed, Ucapped};
information = {fixedInfo, relaxedInfo, cappedInfo};
for index = 1:numel(solutions)
    info = information{index};
    independentlyEvaluatedResidual = trueResidualFunction(solutions{index});
    assert(info.iterations >= 1 && info.iterations <= maximumIteration);
    assert(all(isfinite(info.eta)));
    assert(abs(info.true_relative_residual(end) - ...
        independentlyEvaluatedResidual) < 1e-12);
    assert(info.solution_assembly_count == 1);
end

assert(all(cappedInfo.eta <= 1e-2 * (1 + 10 * eps)));
fprintf('Fixed, relaxed, and capped Tucker GMRES tests passed.\n');

end
