function test_tucker_roundsum_rhosvd
%TEST_TUCKER_ROUNDSUM_RHOSVD Validate RoundSum and Algorithm 5.8.
%
% These are small correctness checks. They do not measure performance and
% they do not produce dissertation experiment results.

add_toolboxes();
rng(43, 'twister');


%% 1. Compare RoundSum with an exact small weighted sum

tensorDimensions = [5, 4, 3];
X = hosvd(tensor(randn(tensorDimensions)), 1e-13, 'verbosity', 0);
Y = hosvd(tensor(randn(tensorDimensions)), 1e-13, 'verbosity', 0);
coefficients = [1.3; -0.45];
exactSum = tucker_axpby_exact(X, coefficients(1), Y, coefficients(2));

[roundSum, roundInfo] = tucker_roundsum_rhosvd( ...
    {X; Y}, coefficients, tensorDimensions, 1e-13, ...
    tensorDimensions, 701);
[sameRoundSum, sameRoundInfo] = tucker_roundsum_rhosvd( ...
    {X; Y}, coefficients, tensorDimensions, 1e-13, ...
    tensorDimensions, 701);
[noDiagnosticRoundSum, noDiagnosticInfo] = tucker_roundsum_rhosvd( ...
    {X; Y}, coefficients, tensorDimensions, 1e-13, ...
    tensorDimensions, 701, false);

roundSumRelativeError = norm(full(roundSum) - full(exactSum)) / ...
    norm(full(exactSum));
reproducibilityError = norm(full(roundSum) - full(sameRoundSum)) / ...
    norm(full(roundSum));
diagnosticSwitchError = norm( ...
    full(roundSum) - full(noDiagnosticRoundSum)) / norm(full(roundSum));

assert(roundSumRelativeError < 1e-11, ...
    'Full-range RoundSum does not reproduce the small exact Tucker sum.');
assert(reproducibilityError < 1e-14, ...
    'The same RoundSum seed did not reproduce the result.');
assert(diagnosticSwitchError < 1e-14, ...
    'Disabling error diagnostics changed the RoundSum output.');
assert(~noDiagnosticInfo.error_diagnostics_measured && ...
    noDiagnosticInfo.error_diagnostic_time_sec == 0 && ...
    isnan(noDiagnosticInfo.relative_range_error) && ...
    isnan(noDiagnosticInfo.relative_total_error), ...
    'The RoundSum timing switch did not suppress exact error diagnostics.');
assert(roundInfo.map_distribution == "standard_normal", ...
    'RoundSum did not report standard Gaussian factor matrices.');
assert(roundInfo.map_factor_entry_variance == 1, ...
    'RoundSum reported the wrong Gaussian variance.');
assert(roundInfo.maps_are_new_for_call && ...
    sameRoundInfo.maps_are_new_for_call, ...
    'A nonzero RoundSum call must draw a new map collection.');

mapsOne = create_tucker_roundsum_maps( ...
    tensorDimensions, tensorDimensions, 701);
mapsTwo = create_tucker_roundsum_maps( ...
    tensorDimensions, tensorDimensions, 702);
assert(~isequal(mapsOne.factors{1}{2}, mapsTwo.factors{1}{2}), ...
    'Different RoundSum seeds produced identical factor maps.');

rankConstraintCaught = false;
try
    tucker_roundsum_rhosvd( ...
        {X; Y}, coefficients, [2, 2, 2], 1e-10, [3, 2, 2], 703);
catch exception
    rankConstraintCaught = contains(exception.message, 'R_n <= k_n');
end
assert(rankConstraintCaught, ...
    'RoundSum did not enforce the condition R_n <= k_n.');


%% 2. Check the exact fixed-linear residual column in Algorithm 5.8

N = 6;
h = 1 / (N + 1);
onesVector = ones(N, 1);
A1 = spdiags( ...
    [-onesVector, 2 * onesVector, -onesVector], -1:1, N, N) / h^2;
gridPoints = (1:N).' / (N + 1);
gaussianVector = exp(-10 * (gridPoints - 1/2).^2);
F = ttensor(tensor(1, [1, 1, 1]), ...
    {gaussianVector, gaussianVector, gaussianVector});
U0 = 0 * F;
normF = norm(F);

operatorTermsFunction = @(U) poisson_action_tucker_terms(U, A1);
originalResidualFunction = @(U) ...
    true_residual_tucker_poisson(U, F, A1);
preconditionedResidualNormFunction = @(U) ...
    normF * true_residual_tucker_poisson(U, F, A1);
residualSketch = create_tucker_row_khatri_rao_sketch( ...
    [N, N, N], 30, 811);

basisSettings.range_sketch_sizes = [N, N, N];
basisSettings.compression_tolerance = 1e-12;
basisSettings.maximum_ranks = [N, N, N];
basisSettings.random_seed = 1200;
basisSettings.algorithm_variant = "exact_sketch_before_roundsum";
basisSettings.adaptive_rank_selection = false;
solutionSettings = basisSettings;
solutionSettings.random_seed = 2200;

[~, solverInfo] = tucker_sgmres_left_preconditioned_rhosvd( ...
    operatorTermsFunction, @identity_tucker_fixed_linear_preconditioner, ...
    F, U0, 4, residualSketch, 1e-14, 2, ...
    basisSettings, solutionSettings, originalResidualFunction, ...
    preconditionedResidualNormFunction, false, Inf);

V1 = (1 / normF) * F;
[firstOperatorTerms, firstOperatorCoefficients] = ...
    poisson_action_tucker_terms(V1, A1);
expectedFirstColumn = apply_tucker_row_khatri_rao_sketch_sum( ...
    firstOperatorTerms, firstOperatorCoefficients, residualSketch);
firstColumnRelativeError = norm( ...
    solverInfo.C(:, 1) - expectedFirstColumn) / norm(expectedFirstColumn);

assert(firstColumnRelativeError < 1e-11, ...
    'The first residual column was not sketched before RoundSum.');
assert(solverInfo.exact_fixed_linear_sketch_before_roundsum, ...
    'The solver did not report the exact sketch-before-rounding contract.');
assert(~solverInfo.fixed_linear_preconditioner_rounding_performed, ...
    'The solver allowed recompression inside the fixed preconditioner.');
assert(numel(unique(solverInfo.basis_roundsum_seeds)) == ...
    numel(solverInfo.basis_roundsum_seeds), ...
    'The solver reused a RoundSum seed inside one cycle.');
assert(all(diff(solverInfo.basis_roundsum_seeds) == 1), ...
    'The basis RoundSum seed schedule is not the fresh-map rule.');
assert(isfinite(solverInfo.true_relative_residual(end)), ...
    'The independently evaluated final true residual is not finite.');
assert(solverInfo.true_relative_residual(end) < ...
    solverInfo.true_relative_residual(1), ...
    'The RHOSVD Tucker sGMRES smoke test did not reduce the true residual.');


%% 3. Check that the omitted option defaults to paper-order Algorithm 5.8

paperSettings.compression_tolerance = 1e-12;
paperSettings.random_seed = 3100;
paperSettings.measure_error_diagnostics = true;
paperSettings.adaptive_rank_selection = true;
paperSettings.oversampling = 2;
paperSettings.maximum_rank = N;
paperSolutionSettings = paperSettings;
paperSolutionSettings.random_seed = 4100;

[~, paperInfo] = tucker_sgmres_left_preconditioned_rhosvd( ...
    operatorTermsFunction, @identity_tucker_fixed_linear_preconditioner, ...
    F, U0, 4, residualSketch, 1e-14, 2, paperSettings, ...
    paperSolutionSettings, originalResidualFunction, ...
    preconditionedResidualNormFunction, false, Inf, [2; 4]);

[roundedInitialResidual, ~] = tucker_roundsum_rhosvd_adaptive( ...
    {F}, 1, paperSettings.oversampling, ...
    paperSettings.compression_tolerance, paperSettings.maximum_rank, ...
    paperSettings.random_seed, true);
paperV1 = (1 / norm(roundedInitialResidual)) * roundedInitialResidual;
[paperOperatorTerms, paperOperatorCoefficients] = ...
    poisson_action_tucker_terms(paperV1, A1);
[roundedPaperOperator, adaptiveInfo] = ...
    tucker_roundsum_rhosvd_adaptive( ...
    paperOperatorTerms, paperOperatorCoefficients, ...
    paperSettings.oversampling, paperSettings.compression_tolerance, ...
    paperSettings.maximum_rank, paperSettings.random_seed + 1, true);
expectedPaperFirstColumn = apply_tucker_row_khatri_rao_sketch( ...
    roundedPaperOperator, residualSketch);
paperFirstColumnRelativeError = norm( ...
    paperInfo.C(:, 1) - expectedPaperFirstColumn) / ...
    norm(expectedPaperFirstColumn);

assert(paperFirstColumnRelativeError < 1e-11, ...
    'The paper-order path did not sketch the rounded operator result.');
assert(~paperInfo.exact_fixed_linear_sketch_before_roundsum && ...
    paperInfo.rounded_operator_sketch_after_roundsum, ...
    'The paper-order sketch contract was not reported correctly.');
assert(paperInfo.algorithm_variant == "paper_order", ...
    'An omitted algorithm_variant did not select paper_order.');
assert(paperInfo.batch_local_projection_coefficients && ...
    ~paperInfo.local_mgs_is_batch_formula_adaptation, ...
    'The paper-order path did not use batch local coefficients.');
assert(adaptiveInfo.adaptive_rank_selection && ...
    all(adaptiveInfo.effective_rank_estimates >= 1), ...
    'Adaptive RoundSum did not report valid effective ranks.');
assert(paperInfo.true_relative_residual(end) < ...
    paperInfo.true_relative_residual(1), ...
    'The paper-order Algorithm 5.8 smoke test did not reduce the residual.');
assert(isequal(paperInfo.true_residual_iteration, [0; 2; 4]), ...
    'The paper-order path did not record the requested checkpoints.');
assert(numel(paperInfo.true_relative_residual) == 3 && ...
    all(isfinite(paperInfo.true_relative_residual)), ...
    'The RHOSVD checkpoint true-residual history is incomplete.');

[~, fullArnoldiInfo] = tucker_gmres_left_preconditioned_rhosvd( ...
    operatorTermsFunction, @identity_tucker_fixed_linear_preconditioner, ...
    F, U0, 4, 1e-14, paperSettings, paperSolutionSettings, ...
    originalResidualFunction, preconditionedResidualNormFunction, ...
    false, Inf);
assert(fullArnoldiInfo.true_relative_residual(end) < ...
    fullArnoldiInfo.true_relative_residual(1), ...
    'The full Arnoldi RHOSVD control did not reduce the true residual.');
assert(all(cellfun(@(oneInfo) ...
    oneInfo.adaptive_rank_selection, fullArnoldiInfo.roundsum_info)), ...
    'The full Arnoldi control did not use adaptive RoundSum.');


%% 4. Check safe return for an already solved initial system

identityTermsFunction = @(U) one_term_identity_operator(U);
identityTrueResidual = @(U) ...
    norm(tucker_axpby_exact(F, 1, U, -1)) / normF;
identityResidualNorm = @(U) ...
    norm(tucker_axpby_exact(F, 1, U, -1));

[zeroSolution, zeroInfo] = ...
    tucker_sgmres_left_preconditioned_rhosvd( ...
    identityTermsFunction, @identity_tucker_fixed_linear_preconditioner, ...
    F, F, 2, residualSketch, 1e-12, 1, basisSettings, ...
    solutionSettings, identityTrueResidual, identityResidualNorm, ...
    false, Inf);

assert(zeroInfo.iterations == 0 && ...
    zeroInfo.stop_reason == "zero_initial_residual", ...
    'The zero initial residual safeguard did not return before division.');
assert(norm(full(zeroSolution) - full(F)) == 0, ...
    'The zero residual safeguard changed the exact initial solution.');


%% 5. Reject a preconditioner that rounds before the sketch

roundedPreconditionerCaught = false;
try
    tucker_sgmres_left_preconditioned_rhosvd( ...
        operatorTermsFunction, @invalid_rounded_preconditioner, ...
        F, U0, 2, residualSketch, 1e-12, 1, basisSettings, ...
        solutionSettings, originalResidualFunction, ...
        preconditionedResidualNormFunction, false, Inf);
catch exception
    roundedPreconditionerCaught = contains( ...
        exception.message, 'fixed and linear');
end
assert(roundedPreconditionerCaught, ...
    'The solver accepted recompression inside the fixed preconditioner.');

fprintf('\nRHOSVD RoundSum and Tucker sGMRES correctness test\n');
fprintf('Full-range RoundSum relative error     %.3e\n', ...
    roundSumRelativeError);
fprintf('Repeated-seed reproducibility error    %.3e\n', ...
    reproducibilityError);
fprintf('Diagnostic-switch output error         %.3e\n', ...
    diagnosticSwitchError);
fprintf('Exact first sketch-column error        %.3e\n', ...
    firstColumnRelativeError);
fprintf('Paper-order first-column error         %.3e\n', ...
    paperFirstColumnRelativeError);
fprintf('Four-step final true residual          %.3e\n', ...
    solverInfo.true_relative_residual(end));
fprintf('All RHOSVD safeguards passed.\n\n');

end


function [terms, coefficients, info] = one_term_identity_operator(U)
%ONE_TERM_IDENTITY_OPERATOR Exact formal representation of I(U).

terms = {U};
coefficients = 1;
info.rounding_performed = false;

end


function [Z, info] = invalid_rounded_preconditioner(Y)
%INVALID_ROUNDED_PRECONDITIONER Deliberately violate the solver contract.

Z = Y;
info.rounding_performed = true;

end
