function run_all_tests()
%RUN_ALL_TESTS Run the focused correctness tests for the public release.

add_toolboxes();

tests = { ...
    @test_sgmres_trunc_arnoldi, ...
    @test_tucker_gmres_foundation, ...
    @test_tucker_sgmres_foundation, ...
    @test_tucker_roundsum_rhosvd, ...
    @test_sthosvd_tail_stability, ...
    @test_poisson_fast_diagonalization_tucker_preconditioner, ...
    @test_poisson_fast_diagonalization_tucker_preconditioner_4d, ...
    @test_poisson_fast_diagonalization_full_gmres, ...
    @test_poisson_preconditioned_tucker_gmres};

for testIndex = 1:numel(tests)
    testFunction = tests{testIndex};
    fprintf("\nRunning %s\n", func2str(testFunction));
    testFunction();
end

fprintf("\nAll %d focused tests passed.\n", numel(tests));
end
