function [U, info] = tucker_gmres_left_preconditioned_fixed_restarted( ...
    originalOperatorFunction, preconditionerFunction, F0, U0, ...
    restartLength, maximumCycles, targetTolerance, ...
    compressionTolerance, originalTrueResidualFunction, ...
    preconditionedResidualNormFunction, displayProgress, ...
    maximumBasisStorageEntries, maximumMultilinearRank)
%TUCKER_GMRES_LEFT_PRECONDITIONED_FIXED_RESTARTED Fixed restarted control.
%
% This applies Algorithm 5.6 to the left-preconditioned system while keeping
% one fixed Tucker recompression tolerance.

if nargin < 11
    displayProgress = false;
end

if nargin < 12
    maximumBasisStorageEntries = Inf;
end

if nargin < 13
    maximumMultilinearRank = [];
end

[U, info] = run_restarted_left_preconditioned_tucker_gmres( ...
    originalOperatorFunction, preconditionerFunction, F0, U0, ...
    restartLength, maximumCycles, targetTolerance, ...
    compressionTolerance, "fixed", originalTrueResidualFunction, ...
    preconditionedResidualNormFunction, displayProgress, ...
    maximumBasisStorageEntries, maximumMultilinearRank);

end
